import { useCallback } from 'react';
import { useProjectContext } from '../context/ProjectContext';
import { CONFIG } from '../config/environment';

/**
 * useProjects Hook
 * Convenience hook for accessing project operations
 * Wraps ProjectContext with additional utilities
 */
const useProjects = () => {
  const context = useProjectContext();

  const {
    projects,
    loading,
    error,
    getProjectById,
    createProject,
    updateProject,
    deleteProject,
    saveProject,
    getRecentProjects,
    searchProjects,
    getProjectsByType,
    loadProjects,
  } = context;

  /**
   * Get initial projects for welcome page (3 rows)
   */
  const getInitialProjects = useCallback(() => {
    return getRecentProjects(CONFIG.APP.MAX_PROJECTS_DISPLAY);
  }, [getRecentProjects]);

  /**
   * Load more projects (for show more functionality)
   */
  const [hasMore, setHasMore] = useCallback(() => {
    return projects.length > CONFIG.APP.MAX_PROJECTS_DISPLAY;
  }, [projects]);

  /**
   * Get projects for display (initial or all)
   */
  const [displayProjects, setDisplayProjects] = useCallback((showAll = false) => {
    if (showAll) {
      return projects;
    }
    return getInitialProjects();
  }, [projects, getInitialProjects]);

  /**
   * Duplicate a project
   */
  const duplicateProject = useCallback(
    async (projectId) => {
      const project = getProjectById(projectId);
      if (!project) return null;

      const duplicatedProject = {
        ...project,
        name: `${project.name} (Copy)`,
        id: undefined, // Will be generated by createProject
      };

      return createProject(duplicatedProject);
    },
    [getProjectById, createProject]
  );

  /**
   * Get project statistics
   */
  const getStats = useCallback(() => {
    const visualizers = getProjectsByType('visualizer').length;
    const tracers = getProjectsByType('tracer').length;
    const total = projects.length;

    const languages = {};
    projects.forEach((project) => {
      languages[project.language] = (languages[project.language] || 0) + 1;
    });

    return {
      total,
      visualizers,
      tracers,
      languages,
    };
  }, [projects, getProjectsByType]);

  /**
   * Export project as JSON
   */
  const exportProject = useCallback(
    (projectId) => {
      const project = getProjectById(projectId);
      if (!project) return null;

      const dataStr = JSON.stringify(project, null, 2);
      const dataBlob = new Blob([dataStr], { type: 'application/json' });
      const url = URL.createObjectURL(dataBlob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `${project.name}.json`;
      link.click();
      
      URL.revokeObjectURL(url);
      
      return project;
    },
    [getProjectById]
  );

  /**
   * Import project from JSON
   */
  const importProject = useCallback(
    async (jsonData) => {
      try {
        const projectData = typeof jsonData === 'string' ? JSON.parse(jsonData) : jsonData;
        
        // Remove id to create new project
        const newProjectData = {
          ...projectData,
          id: undefined,
          name: `${projectData.name} (Imported)`,
        };
        
        return createProject(newProjectData);
      } catch (error) {
        console.error('Error importing project:', error);
        throw new Error('Invalid project file');
      }
    },
    [createProject]
  );

  return {
    // From context
    projects,
    loading,
    error,
    getProjectById,
    createProject,
    updateProject,
    deleteProject,
    saveProject,
    getRecentProjects,
    searchProjects,
    getProjectsByType,
    loadProjects,
    
    // Additional utilities
    getInitialProjects,
    hasMore: projects.length > CONFIG.APP.MAX_PROJECTS_DISPLAY,
    loadMore: () => projects,
    duplicateProject,
    getStats,
    exportProject,
    importProject,
  };
};

export default useProjects;
